apiVersion: apps/v1
kind: Deployment
metadata:
  name: nurchik-web
spec:
  replicas: 5
  selector:
    matchLabels:
      app: nurchik-web
  template:
    metadata:
      labels:
        app: nurchik-web
    spec:
      containers:
        - name: web
          image: nur4ike/nurchik-cicd:metrics-v1
          ports:
            - containerPort: 80

        - name: nginx-exporter
          image: nginx/nginx-prometheus-exporter:1.1.0
          args:
            - --nginx.scrape-uri=http://127.0.0.1:80/stub_status
          ports:
            - name: metrics
              containerPort: 9113


