apiVersion: v1
kind: Service
metadata:
  name: nurchik-web-metrics
  labels:
    app: nurchik-web
spec:
  selector:
    app: nurchik-web
  ports:
    - name: metrics
      port: 9113
      targetPort: 9113

